format = """
$custom\
[î‚´](bg:#828df3 fg:#000000)\
$directory\
[î‚´](fg:#828df3 bg:#d7db4f)\
$git_branch\
$git_status\
[î‚´](fg:#d7db4f bg:#e6dc74)\
$nodejs\
$rust\
$golang\
$php\
[î‚´](fg:#e6dc74 bg:#e39a50)\
$time\
[î‚´](fg:#e39a50 bg:#d66eae)\
$cmd_duration\
$status\
[î‚´ ](fg:#d66eae)\
\n$character"""

command_timeout = 2000

[custom.logo1]
command = '''echo -n "â–‘â–’â–“"'''
when = "true"
format = '[$output]($style)'
style = "fg:#000000"

[custom.logo2]
command = '''echo -n "hello"'''
when = "true"
format = '[$output]($style)'
style = "fg:#d7db4f bg:#000000"

[custom.logo3]
command = '''echo -n "world"'''
when = "true"
format = '[$output]($style)'
style = "fg:#d66eae bg:#000000"

[custom.logo4]
command = '''echo -n ";)  "'''
when = "true"
format = '[$output]($style)'
style = "fg:#828df3 bg:#000000"

[directory]
style = "fg:#090c0c bg:#828df3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[git_branch]
symbol = "ï˜"
style = "bg:#d7db4f"
format = '[[ $symbol $branch ](fg:#090c0c bg:#d7db4f)]($style)'

[git_status]
style = "bg:#d7db4f"
conflicted = 'âš”ï¸'
ahead = 'â«'
behind = 'â¬'
diverged = 'ğŸ”€'
up_to_date = 'âœ“'
untracked = 'ğŸ†•'
stashed = 'ğŸ“¦'
modified = 'âœï¸'
staged = 'âœ…'
renamed = 'ğŸ”'
deleted = 'âŒ'
format = '([$all_status]($style))'

[nodejs]
symbol = "îœ˜"
style = "bg:#e6dc74"
format = '[[ $symbol ($version) ](fg:#090c0c bg:#e6dc74)]($style)'

[rust]
symbol = "î¨"
style = "bg:#e6dc74"
format = '[[ $symbol ($version) ](fg:#090c0c bg:#e6dc74)]($style)'

[golang]
symbol = "ï³‘"
style = "bg:#e6dc74"
format = '[[ $symbol ($version) ](fg:#090c0c bg:#e6dc74)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:#e6dc74"
format = '[[ $symbol ($version) ](fg:#090c0c bg:#e6dc74)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#e39a50"
format = '[[ ïº $time ](fg:#090c0c bg:#e39a50)]($style)'

[cmd_duration]
min_time = 60000
format = '[[ took $duration ](fg:#090c0c bg:#d66eae)]($style)'
style = "fg:#090c0c bg:#d66eae"

[status]
disabled = false
format = '[[ âŒ ](fg:#090c0c bg:#d66eae)]($style)'
style = "fg:#090c0c bg:#d66eae"
